---
rhbase_repositories:
  - epel-release

rhbase_install_packages:
  - bash-completion
  - policycoreutils
  - setroubleshoot-server
  - tree
  - vim-enhanced
  - tcpdump

rhbase_firewall_allow_services:
  - http
  - https
  - pop3
  - pop3s
  - imap
  - imaps
  - smtp
  - smtps
  - smtp-submission

rhbase_users:
  - name: johndoe
    groups:
      - users
    password: "$1$WIFkXf07$HQZFgDlnfpSd9B.8McNcf."
    shell: /sbin/nologin

rhbase_selinux_booleans:
  - httpd_can_network_connect

rhbase_firewall_allow_ports:
  - 9100/tcp # Dit is nodig om de server te monitoren

postfix_myhostname: mail.green.local
postfix_mydomain: green.local
postfix_home_mailbox: /mail
postfix_ldap: "true"
ldap_domainname: green.local
ldap_dcname: alfa1

