---
rhbase_repositories:
  - epel-release

rhbase_install_packages:
  - bash-completion
  - policycoreutils
  - setroubleshoot-server
  - tree
  - vim-enhanced
  - tcpdump

rhbase_firewall_allow_services:
  - http
  - https
  - pop3
  - pop3s
  - imap
  - imaps
  - smtp
  - smtps
  - smtp-submission

#DNS SERVER
dns_nameservers: 
  - DNS1=172.16.1.66

rhbase_users:
  - name: johndoe
    groups:
      - users
      - wheel
    # Password = test123
    password: "$6$rzSe0ya3TumnQAGo$oJfY6KB/GhlaTeL98CjQ9.KgciX60R/iEqaPkyyTqUUACKaaRD2MjcaPWPkk7ZFO4v.9iDfYlWo7E/cboy1nP0"
    shell: /sbin/nologin

  - name: ericdoe
    groups:
      - users
      - wheel
    password: "$1$WIFkXf07$HQZFgDlnfpSd9B.8McNcf."
    shell: /sbin/nologin

rhbase_selinux_booleans:
  - httpd_can_network_connect

rhbase_firewall_allow_ports:
  - 9100/tcp # Dit is nodig om de server te monitoren

postfix_myhostname: 'mail.green.local'
postfix_mydomain: 'green.local'
postfix_home_mailbox: 'mail/'
postfix_mynetwork: 172.16.1.64/27
ldap_dcname: alfa1
ldap_domainname: green
ldap_root_domain: local
postfix_ldap: false

httpd_scripting: 'php'
Squirrelmail_domain: green.local
Squirrelmail_imapServerAddress: 172.16.1.68
Squirrelmail_smtpServerAddress: 172.16.1.68
Squirrelmail_imap_port: 143
Squirrelmail_smtp_port: 25
