---
rhbase_firewall_allow_services:
  - http
  - https
rhbase_firewall_allow_ports:
  - 9090/tcp
  - 3000/tcp
  - 9116/tcp

dns_nameservers: ['172.16.1.66', '10.0.2.3']

prometheus_scrape_jobs:
  - job_name: "snmp"
    metrics_path: "/snmp"
    static_configs:
    - targets:
      - "{{ ansible_host }}:9116"



grafana_security:
  admin_user: admin
  admin_password: oscar1
grafana_datasources:
  - name: "prometheus"
    type: "prometheus"
    access: proxy
    url: 'http://localhost:9090'
    basicAuth: false
grafana_dashboards:
  - dashboard_id: 10645
    revision_id: 1
    datasource: 'prometheus'
  - dashboard_id: 2939
    revision_id: 8
    datasource: 'prometheus'
  - dashboard_id: 9901
    revision_id: 1
    datasource: 'prometheus'
  - dashboard_id: 1666
    revision_id: 1
    datasource: 'prometheus'
  - dashboard_id: 9908
    revision_id: 1
    datasource: 'prometheus'
