---
prometheus_targets:
  node:
  - targets:
    - 172.16.1.5:9100
    labels:
      env: Oscar1
grafana_security:
  admin_user: admin
  admin_password: oscar1
grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: 'http://localhost:9090'
    basicAuth: false