# host vars papa1.yml
---
# vagrant host info:
# name: papa1
# mac: '08:00:27:66:5D:0A'
# ip: 172.16.1.6

#--------------------vars for pxeserver role-----------------------------------
#Subdirectory under TFTP root for PXE specific files (default = pxelinux)
#pxeserver_directory: 

#default adress of the PXE server (took the same ip from vagrant-hosts)
pxeserver_ip: 172.16.1.6
#default gateway: 172.16.1.62 (do we do anything with this?)

pxeserver_images:
  - name: centos7_x86_64  #unique identifier for the image
    default: true   #true for the default image
    kernel_url: http://ftp.belnet.be/ftp.centos.org/7/os/x86_64/isolinux/vmlinuz  #URL where to download the kernel image
    initrd_url: http://ftp.belnet.be/ftp.centos.org/7/os/x86_64/isolinux/initrd.img #URL where to download the initrd image
    # kickstart_url: #URL where to download the kickstart file.
    # kickstart_path: #Location where to copy the kickstart file from
    label: CentOS 7 x86_64 #Label for the PXE boot menu entry of this image


#--------------------vars for tftp role-----------------------------------

#--------------------vars for dhcp role-----------------------------------
# dhcp_subnets:
#       - ip: 192.168.50.0
#         netmask: 255.255.255.0