---

    rhbase_firewall_allow_services: # DNS toelaten door Firewall
      - dns

    dnsmasq_domain: 'green.local' # Juiste Domain

    dnsmasq_domain_needed: 'false' # Forward local requests

    dnsmasq_listen_address: 172.16.1.70

    dnsmasq_upstream_servers:
      - /green.local/172.16.1.66 # ns1.green.local
      - /green.local/172.16.1.67 # ns2.green.local

      - 8.8.8.8 # Google DNS