- name: Create unprivileged user for node exporter
  user:
    name: "{{ node_exporter_user }}"
    create_home: no
    system: yes

- name: Create directory for node exporter
  file:
    path: "{{ node_exporter_directory }}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: 700

- name: Download node_exporter binary and verify integrity
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz
    checksum: "sha256:b2503fd932f85f4e5baf161268854bf5d22001869b84f00fd2d1f57b51b72424"

- name: Unarchive node_exporter archive
  unarchive:
      src: /tmp/node_exporter.tar.gz
      dest: "{{ node_exporter_directory }}"
      extra_opts: [--strip-components=1]
      owner: "{{ node_exporter_user }}"
      group: "{{ node_exporter_group }}"

- name: Copy systemd service file
  template:
      src: node_exporter.service.j2
      dest: /etc/systemd/system/{{ node_exporter_service }}.service
  notify:
    - start node exporter

- name: Open node exporter port
  firewalld:
    port: "{{ node_exporter_port }}"
    permanent: yes
    state: enabled
    immediate: yes