# roles/mariadb/defaults/main.yml

mariadb_databases: 
  - name: drupal_echo1
  - name: drupal_mike1

mariadb_users: 
  - { name: drupal_echo1, password: admin , priv: 'drupal_echo1.*:ALL', append_privs: 'yes' }
  - { name: drupal_mike1, password: admin , priv: 'drupal_mike1.*:ALL', append_privs: 'yes' }

mariadb_root_password: admin

mariadb_mirror: yum.mariadb.org
mariadb_version: '10.4'

mariadb_configure_swappiness: true
mariadb_swappiness: 0

# Network configuration (network.cnf)

mariadb_service: mariadb
mariadb_bind_address: '0.0.0.0'

# Server configuration
mariadb_server_cnf: {}

# Custom configuration
mariadb_custom_cnf: {}
