---

#The domain prefix for ldap
openldap_server_domain_name: green.local

#This is the password for admin for openldap 
openldap_server_rootpw: wachtwoord

#The self signed ssl parameters
openldap_server_country: BE
openldap_server_state: oost-vlaanderen
openldap_server_location: gent
openldap_server_organization: IT

openldap_server_enable_ssl: true

#The ldif file
openldap_server_ldif: domain.ldif
...