# servers.yml
---
# Configure server alfa1 with LDAP role
- name: Configure alfa1
  hosts: alfa1
  become: true
  remote_user: root
  roles:
    - LDAP

# Configure bravo 1 (also known as the primary or master DNS server) with DNS BIND
#
- name: Configure bravo1
  hosts: bravo1
  remote_user: root
  gather_facts: yes
  roles:
    - dnsBindBravoCharlie

# Configure charlie 1 (also known as the secondary, backup or slave dns server) with DNS BIND      
- name: Configure charlie1
  gather_facts: yes
  hosts: charlie1
  remote_user: root
  roles:
    - dnsBindBravoCharlie

- hosts: db001
  become: true
  gather_facts: yes
  roles: 
    - november1

- name: Configure Delta1
  hosts: delta1
  become: true
  roles:
    - bertvv.rh-base
    - sepolicy
    - bertvv.httpd
    - bertvv.mailserver
    - bertvv.squirrelmail

#Echo1
- hosts: echo1
  become: true
  roles:
    - common
    - nginx
   # - echo1

#Kilo1
- hosts: kilo1
  become: true
  roles:
    - kilo1-dhcp

#Mike1
- hosts: mike1
  become: true
  roles:
    - common
  # - mike1

# Configure oscar 1: monitoring server
#
#- hosts: oscar1
#  become: true
#  gather_facts: yes
#  roles:
#  - cloudalchemy.prometheus
#  - cloudalchemy.grafana

<<<<<<< Updated upstream
- hosts: oscar1
  become: true
  gather_facts: yes
  roles:
  - cloudalchemy.prometheus
  - cloudalchemy.grafana
  - cloudalchemy.node-exporter

- hosts: papa1
  become: true
  roles: 
    - papa1-pxeserver
=======
#- hosts: papa1
#  become: true
#  roles: 
#    - papa1-pxeserver
>>>>>>> Stashed changes
