# servers.yml
---
# Configure server alfa1 with LDAP role
- name: Configure alfa1
  hosts: alfa1
  remote_user: root
  roles:
    - LDAP

# Configure bravo 1 (also known as the primary or master DNS server) with DNS BIND
#
- name: Configure bravo1
  hosts: bravo1
  remote_user: root
  roles:
    - bravo1

# Configure charlie 1 (also known as the secondary, backup or slave dns server) with DNS BIND      
- name: Configure charlie1
  hosts: charlie1
  remote_user: root
  roles:
    - charlie1

- hosts: db001
  become: true
  gather_facts: yes
  roles: 
    - november1

# Configure oscar 1: monitoring server

- hosts: oscar1
  become: true
  gather_facts: yes
  roles:
  - oscar1
  - oscar1-grafana
  vars:
    prometheus_targets:
      node:
      - targets:
        - 172.16.1.5:9090
        labels:
          env: Oscar1
    grafana_security:
      admin_user: admin
      admin_password: oscar1
