# servers.yml
---
# Configure server alfa1 with LDAP role
- name: Configure alfa1
  hosts: alfa1
  become: true
  remote_user: root
  roles:
    - LDAP

# Configure bravo 1 (also known as the primary or master DNS server) with DNS BIND
#
- name: Configure bravo1
  hosts: bravo1, charlie1
  remote_user: root
  vars:
    bind_zone_dir: /var/local/named-zones
    bind_zone_file_mode: '0660'
    bind_allow_query:
      - any
    bind_listen_ipv6:
      - none
    bind_acls:
      - name: acl1
        match_list:
          - 172.16.0.0/16
    bind_forwarders:
      - '8.8.8.8'
      - '8.8.4.4'
    bind_recursion: false
    bind_query_log: 'data/query.log'
    bind_check_names: 'master ignore'
    bind_zone_master_server_ip: 172.16.1.66
    bind_zone_minimum_ttl: "2D"
    bind_zone_time_to_refresh: "2D"
    bind_zone_time_to_retry: "2H"
    bind_zone_time_to_expire: "2W"
    bind_zone_domains:
      - name: 'green.local'
        networks:
          - '172.16'
        name_servers:
          - ns1.green.local
          - ns2.green.local
        hosts:
          - name: bravo1
            ip: 172.16.1.66
            aliases:
              - www
          - name: charlie1
            ip: 172.16.1.67
          - name: alpha1
            ip: 172.16.1.65
          - name: delta1
            ip: 172.16.1.68
          - name: echo1
            ip: 172.16.1.69
  roles:
    - dnsBindBravoCharlie

# Configure charlie 1 (also known as the secondary, backup or slave dns server) with DNS BIND      
#- name: Configure charlie1
#  hosts: charlie1
#  remote_user: root
#  roles:
#    - charlie1

- hosts: db001
  become: true
  gather_facts: yes
  roles: 
    - november1

#Echo1

- hosts: echo1
  become: true
  roles:
    - webtier

#Mike1

- hosts: mike1
  become: true
  roles:
    - webtier

# Configure oscar 1: monitoring server

- hosts: oscar1
  become: true
  gather_facts: yes
  roles:
  - oscar1
  - oscar1-grafana
  vars:
    prometheus_targets:
      node:
      - targets:
        - 172.16.1.5:9090
        labels:
          env: Oscar1
    grafana_security:
      admin_user: admin
      admin_password: oscar1
