---
#Configure dns servers for all servers
- name: config-dns
  hosts: all:!quebec1
  become: true
  gather_facts: yes
  roles:
    - jdauphant.dns
# Node exporter for monitoring:
- name: node-exporter
  hosts: nodeexporter
  become: true
  roles:
    - node-exporter

# Configure server alfa1 with LDAP role
- name: Configure alfa1
  hosts: alfa1
  become: true
  remote_user: root
  roles:
    - openldap-server
    - openldap-config

# Configure bravo 1 (also known as the primary or master DNS server) with DNS BIND
- name: Configure bravo1
  hosts: bravo1
  remote_user: root
  gather_facts: yes
  # pre_tasks:
  #   - name: Allow tcp port 8053 on selinux
  #     command: sudo semanage port -a -t dns_port_t -p tcp 8053
  #     run_once: true
  pre_tasks:
    - name: Allow tcp port 8053 on SELinux
      seport:
        ports: 8053
        proto: tcp
        setype: dns_port_t
        state: present
  roles:
    - dnsBindBravoCharlie
    - mesaguy.prometheus

# Configure charlie 1 (also known as the secondary, backup or slave dns server) with DNS BIND
- name: Configure charlie1
  gather_facts: yes
  hosts: charlie1
  remote_user: root
  pre_tasks:
    - name: Allow tcp port 8053 on SELinux
      seport:
        ports: 8053
        proto: tcp
        setype: dns_port_t
        state: present
  roles:
    - dnsBindBravoCharlie
    - mesaguy.prometheus

# Configure quebec 1 (forwards the requests to ns12.green.local and ns12.red.local or extern dns-server)
- name: Configure quebec1
  hosts: quebec1
  gather_facts: yes
  remote_user: root
  tasks:
    - name: Copy runbats to quebec1
      copy:
        src: ../test/quebec1/runbats.sh
        dest: /etc/runbats.sh
        owner: vagrant
        group: vagrant
        mode: '0777'
    - name: Copy test.bats to quebec1
      copy:
        src: ../test/quebec1/test.bats
        dest: /etc/test.bats
        owner: vagrant
        group: vagrant
        mode: '0777'
  roles:
    - bertvv.rh-base
    - bertvv.dnsmasq
  post_tasks:
    - name: reload firewalld
      shell: sudo firewall-cmd --reload
- hosts: november1
  become: true
  gather_facts: yes
  roles:
    - mariadb-server
    - mariadb-galera-cluster
    - idealista.prometheus_mysqld_exporter-role
    
#enkel opzetten na week 9 !
#- hosts: november2
  #become: true
  #gather_facts: yes
  #roles:
    #- mariadb-server
    #- mariadb-galera-cluster
    #- idealista.prometheus_mysqld_exporter-role

#- hosts: november3
  #become: true
  #gather_facts: yes
  #roles:
    #- mariadb-server
    #- mariadb-galera-cluster
    #- idealista.prometheus_mysqld_exporter-role

- name: Configure Delta1
  hosts: delta1
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.httpd
    - openldap-client
    - bertvv.mailserver
    - bertvv.squirrelmail
    - infOpen.lynis
    - bats

# Echo1
- hosts: echo1
  become: true
  roles:
    - common
    - drupal
    - cloudalchemy.node-exporter

# Configure kilo1 DHCP server
- hosts: kilo1
  become: true
  roles:
    - kilo1-dhcp

- hosts: lima1
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.samba
    - openldap-client

# Mike1
- hosts: mike1
  become: true
  roles:
    - common
    - drupal
    - cloudalchemy.node-exporter

# Configure oscar 1: monitoring server
- hosts: oscar1
  become: true
  gather_facts: yes
  roles:
    - bertvv.rh-base
    - prometheus
    - grafana
    - snmp-exporter
    - jdauphant.dns

- hosts: papa1
  become: true
  roles:
    - papa1-pxeserver
